### PR TITLE
landing page

### PR DESCRIPTION
**Pull request by Rohan-3000**
Screenshot (50)

### CODE REVIEW

**Review by Ash-exp — CHANGES_REQUESTED** [review]
Required Changes :
1. Prettify the buttons a bit
2. Add an FAQS section below

**Comment by Ash-exp** [comment]
Good job..!! It looks pretty good to me but need to include the above mentioned elements and please attach a mobile view with the updated PR so that we can be assured of the responsiveness of your element 👍

**Comment by Rohan-3000** [comment]
Added accordion and edited the buttons, changed some view css too.
Screenshot (51)
Screenshot (54)
Screenshot (52)
Screenshot (55)
Screenshot (56)
Screenshot (57)

**Review by Debashish-hub — COMMENTED** [review]
Looks pretty fine!

**Review by Ash-exp — APPROVED** [review]
Good job 👍

**Comment by Ash-exp** [comment]
Your code looks great but there's a conflict in your index.tsx. If you can just fetch the code and resolve the conflicts we can merge that at the earliest

**Pull request closed without merging**
